apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: keptn/helm-service
      docker:
        dockerfile: Dockerfile
# Before executing this, install helm-service manually:
# helm install helm-service https://github.com/keptn/keptn/releases/download/0.8.0/helm-service-0.8.0.tgz -n keptn
deploy:
  helm:
    flags:
      upgrade: ["--reuse-values"]
    releases:
      - name: helm-service # needs to be the same name as currently used (check via helm ls -n keptn)
        namespace: keptn # needs to be the same namespace as where the helm-chart is currently deployed
        # upgradeOnChange: true
        # recreatePods: false # don't recreate all pods
        artifactOverrides:
          image: keptn/helm-service
        overrides:
          distributor:
            image:
              tag: 0.8.0
        chartPath: chart
