apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: keptn/lighthouse-service
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    defaultNamespace: keptn
    manifests:
      - deploy/service.yaml
